spring:
  application:
    name: expense-tracker

  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

jwt:
  secret:
    key: ${JWT_SECRET}
  expiration:
    access: ${ACCESS_TOKEN_EXP}
    refresh: ${REFRESH_TOKEN_EXP}